"""
run_topology_frontier.py -- topology-level frontier transfer pilot:
replay an already-optimized local suffix through one of the 5 topologies
(centralized, orchestrate, tree, mesh, star), but with every stage
generated by a real frontier model API instead of a local model. hd-only
(no ft/fu/top/ppl -- see topology_eval_frontier.py).

Usage:
  python3 -u -m masflow.run_topology_frontier \\
      --suffix-source-dir results/run_aca_family_sweep_bfcl/qwen_0.5b \\
      --source-model-key qwen_0.5b \\
      --frontier-model gpt-4o-mini \\
      --topology mesh \\
      --results-dir results/run_topology_frontier/gpt-4o-mini_from_qwen_0.5b

Resumable: any per-task result already written without an "error" key is
skipped.
"""
import argparse
import json
import os
import time

from masflow.tasks_bfcl import TASKS_BFCL
from masflow.frontier_client import FrontierClient
from masflow.topology_eval_frontier import (
    run_depth_variant_eval_frontier, run_fanmerge_eval_frontier, run_deep_tree_eval_frontier,
)

# 5 "preliminaries" topologies + 7 more completing the 12-topology RQ1/RQ2
# grid (4 families x {orig, +1, +2} depth, minus star which is excluded
# from this uniform grid -- see topology_depth_variants.py's docstring).
TOPOLOGY_CHOICES = [
    "centralized", "orchestrate", "tree", "mesh", "star",
    "centralized_d2", "orchestrate_d3", "mesh_d4", "deep_tree",
    "centralized_plus2", "orchestrate_plus2", "tree_plus2", "mesh_plus2",
]


def parse_args():
    ap = argparse.ArgumentParser()
    ap.add_argument("--suffix-source-dir", required=True)
    ap.add_argument("--source-model-key", default="qwen_0.5b")
    ap.add_argument("--frontier-model", required=True)
    ap.add_argument("--topology", required=True, choices=TOPOLOGY_CHOICES)
    ap.add_argument("--results-dir", required=True)
    ap.add_argument("--task-ids", default="all")
    return ap.parse_args()


def main():
    args = parse_args()
    os.makedirs(args.results_dir, exist_ok=True)

    task_ids = [t.task_id for t in TASKS_BFCL] if args.task_ids == "all" else [int(x) for x in args.task_ids.split(",")]
    client = FrontierClient(args.frontier_model)

    print("=" * 72)
    print(f"  TOPOLOGY FRONTIER TRANSFER: {args.topology} | {args.frontier_model} <- {args.source_model_key} suffixes")
    print(f"  Tasks: {len(task_ids)}")
    print("=" * 72, flush=True)

    n_hit = 0
    n_done = 0
    for i, task_id in enumerate(task_ids):
        task = TASKS_BFCL[task_id]
        outfile = os.path.join(args.results_dir, f"task{task_id}.json")
        if os.path.exists(outfile):
            cached = json.load(open(outfile))
            if "error" not in cached:
                print(f"[{i+1}/{len(task_ids)}] task {task_id} -- SKIP (cached)", flush=True)
                n_done += 1
                n_hit += (cached.get("hd_final_verbatim") or cached.get("full_ba_hd")
                          or cached.get("hd_L3_verbatim") or False)
                continue

        suffix_path = os.path.join(args.suffix_source_dir, f"{args.source_model_key}_mcp_beast_task{task_id}.json")
        seed_data = json.load(open(suffix_path))
        suffix_text = seed_data["suffix"]

        t0 = time.time()
        try:
            if args.topology == "star":
                res = run_fanmerge_eval_frontier(client, suffix_text, task)
                hit = res["full_ba_hd"]
            elif args.topology == "deep_tree":
                res = run_deep_tree_eval_frontier(client, suffix_text, task)
                hit = res["hd_L3_verbatim"]
            else:
                res = run_depth_variant_eval_frontier(client, suffix_text, task, args.topology)
                hit = res["hd_final_verbatim"]
            elapsed = time.time() - t0
            n_done += 1
            n_hit += hit
            print(f"[{i+1}/{len(task_ids)}] task {task_id}: {task.expected_tool} -> {task.attack_target_tool}  "
                  f"HIT={hit}  ({elapsed:.1f}s)", flush=True)
            out = {"task_id": task_id, "topology": args.topology, "expected_tool": task.expected_tool,
                   "attack_target_tool": task.attack_target_tool,
                   "source_model_key": args.source_model_key, "frontier_model": args.frontier_model,
                   "elapsed": elapsed, **res}
            json.dump(out, open(outfile, "w"), indent=2)
        except Exception as e:
            import traceback
            traceback.print_exc()
            json.dump({"error": str(e), "task_id": task_id}, open(outfile, "w"), indent=2)

    print("\n" + "=" * 72)
    print(f"  TOPOLOGY FRONTIER TRANSFER COMPLETE ({args.topology}): {n_hit}/{n_done} hits")
    print("=" * 72)


if __name__ == "__main__":
    main()
